#
# Implementation of Multi-scale Turing Patterns in R
#
# R.Benz, 2018-09-28
#
# Use approach outlined in
# https://softologyblog.wordpress.com/2011/07/05/multi-scale-turing-patterns/
#

#' Create a Turing Pattern image
#'
#' compute a turing pattern image
#'
#' @param grid_x size of the output image along the x-dimension
#' @param grid_y size of the ouput image along the y-dimension
#' @param n_itr number of computation iterations (default: 100)
#' @param params parameters for the computation (default: default_params, provided by the package)
#' @param rand_seed random seed to start the computation
#' @param display_intr_imgs display the image with each computation iteration
#' @param color_vals vector of color values for image display
#'
turing_pattern <- function(grid_x, grid_y, n_itr = 100, params = default_params, rand_seed = 12345,
                           display_intr_imgs = FALSE, color_vals = gray.colors(255)) {
  set.seed(rand_seed)

  # Initialize the grid, size grid_x by grid_y, with random numbers between -1 and 1
  tp_grid <- matrix((runif(grid_x * grid_y) * 2) - 1,
                    nrow = grid_x, ncol = grid_y, byrow = TRUE)

  # Check that the activation and inhibition radii are smaller than the grid dimensions
  if (max(params$act_radius) >= grid_x | max(params$act_radius) >= grid_y) {
    error_val <- max(params$act_radius)
    stop(paste0("act_radius parameter value ", error_val, " is >= than supplied grid values {", grid_x, ", ", grid_y, "}\n",
                "  please update the supplied params to ensure act_radius values are smaller than grid dimensions"))
  }

  if (max(params$inhib_radius) >= grid_x | max(params$inhib_radius) >= grid_y) {
    error_val <- max(params$inhib_radius)
    stop(paste0("inhib_radius parameter value ", error_val, " is >= than supplied grid values {", grid_x, ", ", grid_y, "}\n",
                "  please update the supplied params to ensure inhib_radius values are smaller than grid dimensions"))
  }

  pb <- progress::progress_bar$new(
    format = "  computing [:bar] :percent eta: :eta",
    total = n_itr,
    clear = FALSE,
    width = 60
  )

  for (i in 1:n_itr) {
    pb$tick()

    # Suppressing warnings here because gblur is is noisy!
    vals <- suppressWarnings(
      params %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
          activator_mtrx = list(EBImage::gblur(tp_grid, sigma = act_radius, radius = act_radius) * weight),
          inhibitor_mtrx = list(EBImage::gblur(tp_grid, sigma = inhib_radius, radius = inhib_radius) * weight),
          variation_mtrx = list(abs(activator_mtrx - inhibitor_mtrx))
        ) %>%
        dplyr::ungroup()
    )


    # Figure out the scale with the min variation for each x, y
    var_mtrx <- simplify2array(vals$variation_mtrx)

    scale_mtrx <- matrix(rep(0, grid_x * grid_y), nrow = grid_x, ncol = grid_y, byrow = TRUE)
    for (x in 1:dim(var_mtrx)[1]) {
      for (y in 1:dim(var_mtrx)[2]) {
        scale_sel <- which(var_mtrx[x,y,] == min(var_mtrx[x,y,]))

        act_sel <- vals$activator_mtrx[[scale_sel]][x,y]
        inh_sel <- vals$inhibitor_mtrx[[scale_sel]][x,y]

        if (act_sel > inh_sel) {
          tp_grid[x, y] <- tp_grid[x, y] + params$small[scale_sel]
        } else {
          tp_grid[x, y] <- tp_grid[x, y] - params$small[scale_sel]
        }
      }
    }

    min_grid <- min(tp_grid)
    max_grid <- max(tp_grid)
    range_grid <- max_grid - min_grid
    tp_grid <- (tp_grid - min_grid) / range_grid * 2 - 1

    # print the interim images?
    if (display_intr_imgs) {
      show_image(tp_grid, color_vals)
    }
  }

  tp_grid
}


#' Display a Turing Pattern image
#'
#' display a turing pattern image
#'
#' @param tp_grid output turing pattern grid, generated by turing_pattern()
#' @param color_vals vector of color values for image display
#'
show_image <- function(tp_grid, color_vals = hcl.colors(12, "YlOrRd", rev = TRUE)) {
  image(tp_grid, useRaster = TRUE, axes = FALSE, col = color_vals)
}


#' Save a Turing Pattern image
#'
#' save a turing pattern image to a png
#'
#' @param tp_grid output turing pattern grid, generated by turing_pattern()
#' @param color_vals vector of color values for image display
#'
save_image <- function(tp_grid, file_name, color_vals = hcl.colors(12, "YlOrRd", rev = TRUE)) {
  png(file_name, width = ncol(tp_grid), height = nrow(tp_grid))
  par(mar = c(0,0,0,0))
  show_image(tp_grid, color_vals)
  dev.off()
}

